# Generated by Django 5.0.3 on 2026-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
